/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FlashLoanArbitrageurInterface extends Interface {
    getFunction(nameOrSignature: "ADDRESSES_PROVIDER" | "LENDING_POOL" | "executeOperation" | "flashLoanAmount" | "flashLoanToken" | "initiateFlashLoan" | "owner" | "profitRecipient" | "recoverToken" | "renounceOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FlashLoanExecuted" | "OwnershipTransferred" | "ProfitExtracted" | "SwapExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'ADDRESSES_PROVIDER', values?: undefined): string;
encodeFunctionData(functionFragment: 'LENDING_POOL', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeOperation', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'flashLoanAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'flashLoanToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'initiateFlashLoan', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'profitRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverToken', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ADDRESSES_PROVIDER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LENDING_POOL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeOperation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flashLoanAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flashLoanToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateFlashLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'profitRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace FlashLoanExecutedEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish, profit: BigNumberish];
      export type OutputTuple = [token: string, amount: bigint, profit: bigint];
      export interface OutputObject {token: string, amount: bigint, profit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProfitExtractedEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish, recipient: AddressLike];
      export type OutputTuple = [token: string, amount: bigint, recipient: string];
      export interface OutputObject {token: string, amount: bigint, recipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapExecutedEvent {
      export type InputTuple = [fromToken: AddressLike, toToken: AddressLike, fromAmount: BigNumberish, toAmount: BigNumberish];
      export type OutputTuple = [fromToken: string, toToken: string, fromAmount: bigint, toAmount: bigint];
      export interface OutputObject {fromToken: string, toToken: string, fromAmount: bigint, toAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FlashLoanArbitrageur extends BaseContract {
    
    connect(runner?: ContractRunner | null): FlashLoanArbitrageur;
    waitForDeployment(): Promise<this>;

    interface: FlashLoanArbitrageurInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADDRESSES_PROVIDER: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LENDING_POOL: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    executeOperation: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, premium: BigNumberish, initiator: AddressLike, params: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    flashLoanAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    flashLoanToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    initiateFlashLoan: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, params: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    profitRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recoverToken: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADDRESSES_PROVIDER'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LENDING_POOL'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'executeOperation'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, premium: BigNumberish, initiator: AddressLike, params: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'flashLoanAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'flashLoanToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initiateFlashLoan'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, params: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'profitRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverToken'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FlashLoanExecuted'): TypedContractEvent<FlashLoanExecutedEvent.InputTuple, FlashLoanExecutedEvent.OutputTuple, FlashLoanExecutedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProfitExtracted'): TypedContractEvent<ProfitExtractedEvent.InputTuple, ProfitExtractedEvent.OutputTuple, ProfitExtractedEvent.OutputObject>;
getEvent(key: 'SwapExecuted'): TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;

    filters: {
      
      'FlashLoanExecuted(address,uint256,uint256)': TypedContractEvent<FlashLoanExecutedEvent.InputTuple, FlashLoanExecutedEvent.OutputTuple, FlashLoanExecutedEvent.OutputObject>;
      FlashLoanExecuted: TypedContractEvent<FlashLoanExecutedEvent.InputTuple, FlashLoanExecutedEvent.OutputTuple, FlashLoanExecutedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProfitExtracted(address,uint256,address)': TypedContractEvent<ProfitExtractedEvent.InputTuple, ProfitExtractedEvent.OutputTuple, ProfitExtractedEvent.OutputObject>;
      ProfitExtracted: TypedContractEvent<ProfitExtractedEvent.InputTuple, ProfitExtractedEvent.OutputTuple, ProfitExtractedEvent.OutputObject>;
    

      'SwapExecuted(address,address,uint256,uint256)': TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
      SwapExecuted: TypedContractEvent<SwapExecutedEvent.InputTuple, SwapExecutedEvent.OutputTuple, SwapExecutedEvent.OutputObject>;
    
    };
  }