/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'FlashLoanArbitrageur', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FlashLoanArbitrageur__factory>
getContractFactory(name: 'ICurveStableSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ICurveStableSwap__factory>
getContractFactory(name: 'IFlashLoanReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFlashLoanReceiver__factory>
getContractFactory(name: 'ILendingPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILendingPool__factory>
getContractFactory(name: 'ISwapRouter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISwapRouter__factory>

  getContractAt(name: 'FlashLoanArbitrageur', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FlashLoanArbitrageur>
getContractAt(name: 'ICurveStableSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ICurveStableSwap>
getContractAt(name: 'IFlashLoanReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFlashLoanReceiver>
getContractAt(name: 'ILendingPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILendingPool>
getContractAt(name: 'ISwapRouter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISwapRouter>

  deployContract(name: 'FlashLoanArbitrageur', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FlashLoanArbitrageur>
deployContract(name: 'ICurveStableSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICurveStableSwap>
deployContract(name: 'IFlashLoanReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFlashLoanReceiver>
deployContract(name: 'ILendingPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILendingPool>
deployContract(name: 'ISwapRouter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISwapRouter>

  deployContract(name: 'FlashLoanArbitrageur', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FlashLoanArbitrageur>
deployContract(name: 'ICurveStableSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ICurveStableSwap>
deployContract(name: 'IFlashLoanReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFlashLoanReceiver>
deployContract(name: 'ILendingPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILendingPool>
deployContract(name: 'ISwapRouter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISwapRouter>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  