/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICurveStableSwap } from "./ICurveStableSwap";
export type { IFlashLoanReceiver } from "./IFlashLoanReceiver";
export type { ILendingPool } from "./ILendingPool";
export type { ISwapRouter } from "./ISwapRouter";
