/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ICurveStableSwapInterface extends Interface {
    getFunction(nameOrSignature: "N_COINS" | "coins" | "exchange" | "get_dy"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'N_COINS', values?: undefined): string;
encodeFunctionData(functionFragment: 'coins', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'exchange', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'get_dy', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'N_COINS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'coins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exchange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_dy', data: BytesLike): Result;
  }

  

  export interface ICurveStableSwap extends BaseContract {
    
    connect(runner?: ContractRunner | null): ICurveStableSwap;
    waitForDeployment(): Promise<this>;

    interface: ICurveStableSwapInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    N_COINS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    coins: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    exchange: TypedContractMethod<
      [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    get_dy: TypedContractMethod<
      [i: BigNumberish, j: BigNumberish, dx: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'N_COINS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'coins'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'exchange'): TypedContractMethod<
      [i: BigNumberish, j: BigNumberish, dx: BigNumberish, min_dy: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'get_dy'): TypedContractMethod<
      [i: BigNumberish, j: BigNumberish, dx: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }