/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ILendingPoolInterface extends Interface {
    getFunction(nameOrSignature: "borrow" | "deposit" | "flashLoan" | "getUserAccountData" | "repay"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'borrow', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'flashLoan', values: [AddressLike, AddressLike[], BigNumberish[], BigNumberish[], AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserAccountData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'repay', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'borrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flashLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserAccountData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repay', data: BytesLike): Result;
  }

  

  export interface ILendingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILendingPool;
    waitForDeployment(): Promise<this>;

    interface: ILendingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    borrow: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, interestRateMode: BigNumberish, referralCode: BigNumberish, onBehalfOf: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, onBehalfOf: AddressLike, referralCode: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    flashLoan: TypedContractMethod<
      [receiver: AddressLike, assets: AddressLike[], amounts: BigNumberish[], modes: BigNumberish[], onBehalfOf: AddressLike, params: BytesLike, referralCode: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getUserAccountData: TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {totalCollateralETH: bigint, totalDebtETH: bigint, availableBorrowsETH: bigint, currentLiquidationThreshold: bigint, ltv: bigint, healthFactor: bigint }],
      'view'
    >
    

    
    repay: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, rateMode: BigNumberish, onBehalfOf: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'borrow'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, interestRateMode: BigNumberish, referralCode: BigNumberish, onBehalfOf: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, onBehalfOf: AddressLike, referralCode: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'flashLoan'): TypedContractMethod<
      [receiver: AddressLike, assets: AddressLike[], amounts: BigNumberish[], modes: BigNumberish[], onBehalfOf: AddressLike, params: BytesLike, referralCode: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getUserAccountData'): TypedContractMethod<
      [user: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {totalCollateralETH: bigint, totalDebtETH: bigint, availableBorrowsETH: bigint, currentLiquidationThreshold: bigint, ltv: bigint, healthFactor: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'repay'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, rateMode: BigNumberish, onBehalfOf: AddressLike, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }