/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICurveStableSwap } from './ICurveStableSwap.js';
export type { IFlashLoanReceiver } from './IFlashLoanReceiver.js';
export type { ILendingPool } from './ILendingPool.js';
export type { ISwapRouter } from './ISwapRouter.js';