// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IFlashLoanReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IFlashLoanReceiver";
  readonly sourceName: "contracts/interfaces/IFlashLoanReceiver.sol";
  readonly abi: [{"inputs":[],"name":"ADDRESSES_PROVIDER","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"LENDING_POOL","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"premium","type":"uint256"},{"internalType":"address","name":"initiator","type":"address"},{"internalType":"bytes","name":"params","type":"bytes"}],"name":"executeOperation","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IFlashLoanReceiver.sol";
  readonly buildInfoId: "solc-0_8_28-04976e8d1e3a36b5a90801805de99dba7590ec53";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IFlashLoanReceiver"]: IFlashLoanReceiver$Type;
    ["contracts/interfaces/IFlashLoanReceiver.sol:IFlashLoanReceiver"]: IFlashLoanReceiver$Type;
  }
}